# Generated by Django 5.2.3 on 2025-06-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='des/')),
                ('Text_tepa', models.TextField(max_length=40)),
                ('Text_katta', models.TextField(max_length=40, verbose_name='Katta Yozuv bolib chiqadi')),
                ('Text_pas', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bosh Sahifa slideri rasmi va yozuvi',
            },
        ),
    ]
