# Generated by Django 5.2.3 on 2025-06-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortdesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('name', models.TextField(max_length=900)),
            ],
            options={
                'verbose_name_plural': 'Bosh Sahifa qisqa tanishtiruv yozuv va rasm',
            },
        ),
        migrations.AlterField(
            model_name='slider',
            name='rasm',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
