# Generated by Django 5.2.3 on 2025-06-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shortdesc_alter_slider_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(max_length=2000, verbose_name='Batafsil malumot')),
                ('picture', models.ImageField(upload_to='product/', verbose_name="900x650 o'lchamda surat tavsiya etiladi!")),
                ('time', models.TextField(max_length=30, verbose_name='Qurish muddati')),
                ('made', models.TextField(max_length=30, verbose_name='Miqdoi kg')),
            ],
            options={
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
    ]
