# Generated by Django 5.2.3 on 2025-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='hamkor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='hamkorlar/')),
            ],
            options={
                'verbose_name_plural': 'Hamkorlar',
            },
        ),
    ]
