# Generated by Django 5.2.3 on 2025-06-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hamkor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='nweses/', verbose_name="talab etiladi 850x500 dan yuqori o'lcham")),
                ('img2', models.ImageField(blank=True, upload_to='backgraund/', verbose_name="talab etiladi 850x500 dan yuqori o'lcham")),
                ('titl', models.TextField(max_length=100, verbose_name='Sarlavha')),
                ('desc', models.TextField(max_length=1000, verbose_name='Tavsif')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
