# Generated by Django 5.2.3 on 2025-06-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/', verbose_name="961X601 o'lcham tavsiya etiladi")),
                ('desc', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Korxona haqida rasm va tarixi uchun',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL uchun slug'),
        ),
    ]
