# Generated by Django 5.2.3 on 2025-06-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutus_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
