# Generated by Django 5.2.3 on 2025-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_aboutus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='imagebgvideo',
            field=models.ImageField(blank=True, null=True, upload_to='bg/', verbose_name='Video orqa foni'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video fayl'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='desc',
            field=models.TextField(max_length=5000, verbose_name='Korxona tarixi yoki haqida'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.TextField(max_length=50, verbose_name='kompaniya nomi'),
        ),
    ]
