# Generated by Django 5.2.3 on 2025-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_aboutus_imagebgvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL uchun slug'),
        ),
    ]
