# Generated by Django 5.2.3 on 2025-06-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_yangiliklar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='titl',
            field=models.TextField(max_length=900, verbose_name='Sarlavha'),
        ),
    ]
