# Generated by Django 5.2.3 on 2025-06-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_yangiliklar_titl'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='desc2',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Tavsif 2 surat pasida chiqadi'),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='desc',
            field=models.TextField(max_length=1000, verbose_name='Tavsif 1-surat pasida chiqadi'),
        ),
    ]
