# Generated by Django 5.2.3 on 2025-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adress',
            field=models.TextField(max_length=200),
        ),
    ]
