# Generated by Django 5.2.3 on 2025-06-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_contact_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='address',
        ),
    ]
