# Generated by Django 5.2.3 on 2025-06-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_adress_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Tel2',
            field=models.TextField(blank=True, max_length=40, verbose_name="TEl NOMER2 agar bo'lsa"),
        ),
    ]
