# Generated by Django 5.2.3 on 2025-06-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contact_tel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='maps',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
