# Generated by Django 5.2.3 on 2025-06-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_contact_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='maps',
            field=models.TextField(max_length=500),
        ),
    ]
