# Generated by Django 5.2.3 on 2025-06-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_contact_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='desc',
            field=models.TextField(max_length=10000, verbose_name='Tavsif 1-surat pasida chiqadi'),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='desc2',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Tavsif 2 surat pasida chiqadi'),
        ),
    ]
